# Generated by Django 2.0 on 2017-12-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tutor_photo',
            field=models.ImageField(default=None, upload_to='teachers/%Y/%m'),
            preserve_default=False,
        ),
    ]
