# Generated by Django 2.0 on 2017-12-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudor', '0002_tutor_tutor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='teacher_address',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='teacher_email',
            field=models.EmailField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='screen_name',
            field=models.CharField(max_length=100),
        ),
    ]
