# Generated by Django 2.0 on 2017-12-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudor', '0003_auto_20171204_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='alma_mater',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='degree',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='major',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='years_xp',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
