# Generated by Django 2.0 on 2017-12-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudor', '0004_auto_20171205_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seek_name', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(verbose_name='join_date')),
                ('is_parent', models.BooleanField()),
                ('seek_addr', models.CharField(max_length=200)),
                ('desired_subjects', models.CharField(max_length=250)),
            ],
        ),
    ]
