# Generated by Django 2.0 on 2017-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudor', '0005_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='seek_photo',
            field=models.ImageField(default=None, upload_to='seekers/%Y/%m'),
            preserve_default=False,
        ),
    ]
