# Generated by Django 2.0 on 2017-12-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudor', '0006_seeker_seek_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='seekemail',
            field=models.EmailField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
